<center><?php
        session_start();
        if (!isset($_SESSION["loggedin"])) {
            header("location:login_form.php");
            exit;
        }
        if ($_SESSION["type"] !== "accountant") {
            exit("You are not allowed to access this functionality");
        }
        ?></center>
<!DOCTYPE html>
<html>

<head>
    <title>
        Fill Cashup
    </title>
    <link rel="stylesheet" href="mystyle.css">
    <style>
        #staff_detail {
            list-style-type: none;
            margin: 0;
            padding: 0;

            width: 100%;

            background-color: rgba(255, 255, 0, 1);
            position: fixed;
            top: 0;


            overflow: hidden;
            border: 1px solid black;
        }

        li {
            float: left;
            font-size: 20px;
            border-right: 1px solid black;
            color: black;
        }


        form {
            margin-top: 75px;

        }

        body {
            margin: 0;
        }
    </style>
</head>
<a href='cashup_staff_form.php' style='margin-top:35px;position:fixed;'>Go Back</a>
<br><br><br><br><br>
<div style="position:fixed;">
Total Cash : <input type="text" id="display_cash" value="0" readonly >
</div>

<body>



    <?php


    $id = $_SESSION["target_id"];
    $shift = $_SESSION["target_shift"];


    require_once "config.php";

    //checking if the cashup for staff for a particular shift is already filled or not
    $tdate = date("Y-m-d");

    $sqlca = "Select * from cash_up where DATE='$tdate' and ID='$id' and SHIFT='$shift'";
    if ($ca = mysqli_query($link, $sqlca)) {
        if (mysqli_num_rows($ca) == 1) {
            $ca = mysqli_fetch_assoc($ca);
            if ($ca['CASH_COLLECTION'] > 0) {
                exit("<center><br><br>Cashup for the ID $id, $shift is already filled</center>");
            }
        }
    }

    //checking if the shift is validated or not
    $sql0 = "select DATE,BOOTH_NO,NAME from vehicle_details where EMPLOYEE_ID='$id' and SHIFT='$shift' ORDER BY SNO DESC LIMIT 1";
    if ($sol = mysqli_query($link, $sql0)) {
        $sol = mysqli_fetch_row($sol);
        $date = $sol[0];
        $booth_no = $sol[1];
        $name = $sol[2];
        if ($date) {
            $sql1 = "select COUNT(SNO) , SUM(VALIDATED) from vehicle_details where SHIFT='$shift' and DATE='$date'";
            if ($output = mysqli_query($link, $sql1)) {
                $row = mysqli_fetch_row($output);


                if ($row[0] !== $row[1]) {
                    exit("<br><br><center>The shift you have entered is not validated completely</center>");
                }
            }
        } else {
            exit("<br><br><center>Please Check the shift you have entered , it doesn't have any entries for this Staff Id</center>");
        }
    }

    date_default_timezone_set("Asia/Kolkata");
    $time = date("h:i:sa");
    // Adding recovery amount entered by audit officer to the current staff account

    $sql = "select SUM(TOLL),SUM(CORRECT_TOLL) from vehicle_details where EMPLOYEE_ID='$id' and SHIFT='$shift' and DATE='$date'";
    if ($out = mysqli_query($link, $sql)) {
        $out = mysqli_fetch_row($out);
        $diff = $out[0] - $out[1];
        $sys_collection = $out[0];
        $correct_toll = $out[1];

        // checking if the entry is already present or not
        $sqlcheck = "SELECT * FROM cash_up where DATE='$date' and ID='$id' and SHIFT='$shift'";
        if ($check = mysqli_query($link, $sqlcheck)) {
            if (mysqli_num_rows($check) == 0) {

                $sql2 = "INSERT INTO cash_up (DATE,TIME,ID,SHIFT,SYS_COLLECTION,CORRECT_TOLL,RS1,RS2,RS5,RS10,RS20,RS50,RS100,RS200,RS500,RS2000,CASH_COLLECTION,RECOVERY_AMOUNT,BOOTH,NAME,MANUAL_COLLECTION) VALUES ('$date','$time','$id','$shift','$sys_collection','$correct_toll','0','0','0','0','0','0','0','0','0','0','0','$diff','$booth_no','$name','0')";
                if (!$ins = mysqli_query($link, $sql2)) {
                    exit("<br><br><center>Error in inserting recovery amount generated by audit</center>");
                }
            }
        }
    } else {
        echo "<center>not able to fetch sum(toll) and etc.</center>";
    }




    echo "<ul id='staff_detail'>";
    echo "<li>&emsp; DATE : $date&emsp; </li>";
    echo "<li>&emsp; ID : $id &emsp;</li>";
    echo "<li>&emsp; NAME : $name &emsp;</li>";
    echo "<li>&emsp; SHIFT : $shift &emsp;</li>";
    echo "<li>&emsp; BOOTH : $booth_no &emsp;</li>";
    echo "<li>&emsp; System Collection : $sys_collection &emsp;</li>";
    echo "</ul>";
    echo "<a href='logout.php' style='float:right;width:167px;'>Logout</a>";


    ?><center>
        <form method="POST" id="cashup_form" action="cashup_action.php">
            Enter Cash Denomination : (Number of Notes or Coins)<br><br>
            Rs 1 : <input type="number" name="rs1" value='0'oninput="dispcash()" required=True><br><br>
            Rs 2 : <input type="number" name="rs2" value='0' required=True oninput="dispcash()"><br><br>
            Rs 5 : <input type="number" name="rs5" value='0' required=True oninput="dispcash()"><br><br>
            Rs 10 : <input type="number" name="rs10" value='0' required=True oninput="dispcash()"><br><br>
            Rs 20 : <input type="number" name="rs20" value='0' required=True oninput="dispcash()"><br><br>
            Rs 50: <input type="number" name="rs50" value='0' required=True oninput="dispcash()"><br><br>
            Rs 100 : <input type="number" name="rs100" value='0' required=True oninput="dispcash()"><br><br>
            Rs 200 : <input type="number" name="rs200" value='0' required=True oninput="dispcash()"><br><br>
            Rs 500 : <input type="number" name="rs500" value='0' required=True oninput="dispcash()"><br><br>
            Rs 2000 : <input type="number" name="rs2000" value='0' required=True oninput="dispcash()"><br><br>
            <input type="checkbox" name="manual_collection" id="manual_collection" onchange='myFunction()'>Add Manual Collection
            <div id="manual_cash" style="display:none;">
            <br>
                Rs 1 : <input type="number" name="mrs1" value='0' required=True oninput="dispcash()"><br><br>
                Rs 2 : <input type="number" name="mrs2" value='0' required=True oninput="dispcash()"><br><br>
                Rs 5 : <input type="number" name="mrs5" value='0' required=True oninput="dispcash()"><br><br>
                Rs 10 : <input type="number" name="mrs10" value='0' required=True oninput="dispcash()"><br><br>
                Rs 20 : <input type="number" name="mrs20" value='0' required=True oninput="dispcash()"><br><br>
                Rs 50: <input type="number" name="mrs50" value='0' required=True oninput="dispcash()"><br><br>
                Rs 100 : <input type="number" name="mrs100" value='0' required=True oninput="dispcash()"><br><br>
                Rs 200 : <input type="number" name="mrs200" value='0' required=True oninput="dispcash()"><br><br>
                Rs 500 : <input type="number" name="mrs500" value='0' required=True oninput="dispcash()"><br><br>
                Rs 2000 : <input type="number" name="mrs2000" value='0' required=True oninput="dispcash()"><br><br>
            </div><br><br>
            <input type="button" name="confirm" value="Submit" onclick="confirm_submition()">
            

        </form>
        
        <script>
        function confirm_submition(){
            if (confirm("Do You Want To Submit Details , after this no changes can be done "))
                document.getElementById("cashup_form").submit()
        }
        </script>
        
        <?php
        /*if (isset($_POST['submit'])) {
            $rs1 = $_POST["rs1"];
            $rs2 = $_POST["rs2"] * 2;
            $rs5 = $_POST["rs5"] * 5;
            $rs10 = $_POST["rs10"] * 10;
            $rs20 = $_POST["rs20"] * 20;
            $rs50 = $_POST["rs50"] * 50;
            $rs100 = $_POST["rs100"] * 100;
            $rs200 = $_POST["rs200"] * 200;
            $rs500 = $_POST["rs500"] * 500;
            $rs2000 = $_POST["rs2000"] * 2000;




            $cash_collection = $rs1 + $rs2 + $rs5 + $rs10 + $rs20 + $rs50 + $rs100 + $rs200 + $rs500 + $rs2000;
            
            //denomination of coins/notes in variables
            $rs1 = $_POST["rs1"];
            $rs2 = $_POST["rs2"];
            $rs5 = $_POST["rs5"];
            $rs10 = $_POST["rs10"];
            $rs20 = $_POST["rs20"];
            $rs50 = $_POST["rs50"];
            $rs100 = $_POST["rs100"];
            $rs200 = $_POST["rs200"];
            $rs500 = $_POST["rs500"];
            $rs2000 = $_POST["rs2000"];

            //manual cash

            $mrs1 = $_POST["mrs1"];
            $mrs2 = $_POST["mrs2"]*2;
            $mrs5 = $_POST["mrs5"]*5;
            $mrs10 = $_POST["mrs10"]*10;
            $mrs20 = $_POST["mrs20"]*20;
            $mrs50 = $_POST["mrs50"]*50;
            $mrs100 = $_POST["mrs100"]*100;
            $mrs200 = $_POST["mrs200"]*200;
            $mrs500 = $_POST["mrs500"]*500;
            $mrs2000 = $_POST["mrs2000"]*2000;

            $manual_collection_cash=$mrs1+$mrs2+ $mrs5 + $mrs10 + $mrs20 + $mrs50 + $mrs100 + $mrs200 + $mrs500 + $mrs2000;
            $recovery_amount = $cash_collection - $sys_collection + $diff + $manual_collection_cash;
            $name=$_SESSION['name'];


            $sql3 = "UPDATE cash_up set SYS_COLLECTION='$sys_collection',CORRECT_TOLL='$correct_toll',RECOVERY_AMOUNT='$recovery_amount',TIME='$time',CASH_COLLECTION='$cash_collection',RS1='$rs1',RS2='$rs2',RS5='$rs5',RS10='$rs10',RS20='$rs20',RS50='$rs50',RS100='$rs100',RS200='$rs200',RS500='$rs500',RS2000='$rs2000', MANUAL_COLLECTION='$manual_collection_cash' , CASHUP_BY='$name'  where ID='$id' and SHIFT='$shift' and DATE='$date'";
            if ($update = mysqli_query($link, $sql3)) {

                echo "Cashup filled successfully";
                
                header("Refresh:2,url=cashup_staff_form.php");
            } else {
                echo "<br><br><center>error in updating records</center>";

            }
        }*/
        ?>
        <script>
            function myFunction(){
            cb = document.getElementById('manual_collection')
            div = document.getElementById("manual_cash")
            if (cb.checked) {
                div.style.display = "block";
            } else {
                div.style.display = "none";
            }

            };

            function dispcash(){
            var rs1= document.getElementsByName("rs1")[0].value;
            var rs2=document.getElementsByName("rs2")[0].value*2;
            var rs5= document.getElementsByName("rs5")[0].value*5;
            var rs10= document.getElementsByName("rs10")[0].value*10;
            var rs20= document.getElementsByName("rs20")[0].value*20;
            var rs50= document.getElementsByName("rs50")[0].value*50;
            var rs100= document.getElementsByName("rs100")[0].value*100;
            var rs200= document.getElementsByName("rs200")[0].value*200;
            var rs500= document.getElementsByName("rs500")[0].value*500;
            var rs2000= document.getElementsByName("rs2000")[0].value*2000;

            var mrs1= document.getElementsByName("mrs1")[0].value;
            var mrs2=document.getElementsByName("mrs2")[0].value*2;
            var mrs5= document.getElementsByName("mrs5")[0].value*5;
            var mrs10= document.getElementsByName("mrs10")[0].value*10;
            var mrs20= document.getElementsByName("mrs20")[0].value*20;
            var mrs50= document.getElementsByName("mrs50")[0].value*50;
            var mrs100= document.getElementsByName("mrs100")[0].value*100;
            var mrs200= document.getElementsByName("mrs200")[0].value*200;
            var mrs500= document.getElementsByName("mrs500")[0].value*500;
            var mrs2000= document.getElementsByName("mrs2000")[0].value*2000;
            
            var displaycash=document.getElementById("display_cash");
            var cash=parseInt(rs1)+parseInt(rs2)+ parseInt(rs5) + parseInt(rs10) + parseInt(rs20) + parseInt(rs50) + parseInt(rs100) + parseInt(rs200) + parseInt(rs500) + parseInt(rs2000) + parseInt(mrs1)+parseInt(mrs2)+ parseInt(mrs5) + parseInt(mrs10) + parseInt(mrs20) + parseInt(mrs50) + parseInt(mrs100) + parseInt(mrs200) + parseInt(mrs500) + parseInt(mrs2000);
            displaycash.value=cash;
  


};

            
        </script>
    </center>
</body>


</html>
